apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPVerifyServiceAccountToken
metadata:
  name: k8s-pspverify-svc-token
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment","ReplicaSet", "StatefulSet", "DaemonSet"]
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["kube-system"]